version: '3.6'
services:
  server:
    build:
      context: ./server/
    ports:
      - '8765:8765'
    volumes:
      - './server:/app'
    working_dir: /app
    environment:
      LOG_LEVEL: DEBUG
    command: main.py
  client:
    image: node:12-alpine
    ports:
      - '3008:3000'
    depends_on:
      - server
    volumes:
      - './client:/app'
    working_dir: /app
    command: npm start
